### ISSUE TITLE
Error in Importing RMLConverter

### ISSUE THREAD

**Issue by shakeel26** [anuzzolese/pyrml#6]
There is error in import due to which its not possible to run anything.

```
Traceback (most recent call last):
  File "converter.py", line 2, in <module>
    from pyrml import RMLConverter
  File "/pyrml/pyrml/__init__.py", line 1, in <module>
    from pyrml.pyrml import *
  File "/pyrml/pyrml/pyrml.py", line 52
    def __init__(self, map_id: URIRef = None):
                             ^
SyntaxError: invalid syntax

```

Can you explain, how to fix ?

**Comment by anuzzolese** [comment]
Which version of Python you are using?
pyRML requires Python 3.x. It seems you are using Python 2.x

**Comment by shakeel26** [comment]
Thanks for reply, I am using *3.7* , 2.x is too old,

**Comment by anuzzolese** [comment]
How do you run the software?
What are the steps you do?

**Comment by shakeel26** [comment]
I have followed the readme instructions:

1 - Clone repo
2 - then installed `pip install .`  within repo => it was success
3 - Tried example => python converter.py -o artists_places.ttl -f turtle examples/artists/artist-map.ttl 

At the step 3 it was failed.

4 - Then I tried API method also had issue of Import RMLConverter . 

5 - I have tried with my own RML but also same errors of course.

**Comment by anuzzolese** [comment]
If you type on terminal `python -v` what you have back?

**Comment by shakeel26** [comment]
`Python 3.8.0`
Now I tried again the following command  `python converter.py -o artists_places.ttl -f turtle examples/artists/artist-map.ttl`
Now the error is different and you can see in attachment.
![Screenshot from 2022-10-14 18-57-16](https://user-images.githubusercontent.com/45169340/195901358-9f595948-3320-4b04-8abd-6991cd718743.png)

**Comment by anuzzolese** [comment]
The latest issue you are reporting should be fixed by commit [978e224](https://github.com/anuzzolese/pyrml/commit/978e22440a8fa34392723498b60e994912260925) I have just posted. Let me know if it works.

**Comment by houzw** [comment]
similar problem
`rml_converter = RMLConverter()`
```console
Traceback (most recent call last):
  File "test1.py", line 1, in <module>
    from pyrml import RMLConverter
  File "D:\ProgramData\envs\nlp\lib\site-packages\pyrml\__init__.py", line 2, in <module>
    from pyrml.pyrml_core import *
  File "D:\ProgramData\envs\nlp\lib\site-packages\pyrml\pyrml_core.py", line 14, in <module>
    from rdflib.plugins.sparql.processor import prepareQuery
  File "D:\ProgramData\envs\nlp\lib\site-packages\rdflib\plugins\sparql\__init__.py", line 36, in <module>
    from . import operators, parser, parserutils  # noqa: E402
  File "D:\ProgramData\envs\nlp\lib\site-packages\rdflib\plugins\sparql\operators.py", line 23, in <module>
    from pyparsing import ParseResults
ImportError: cannot import name 'ParseResults' from 'pyparsing' (unknown location)
```
Python version is 3.8, installed pyrml use pip
pyparsing already installed
